/* generated by Svelte v3.32.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space,
	text
} from '../web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let nav;
	let a0;
	let img;
	let img_src_value;
	let t0;
	let button;
	let i;
	let t1;
	let div;
	let ul;
	let li0;
	let a1;
	let t2;
	let t3;
	let li1;
	let a2;
	let t4;
	let t5;
	let li2;
	let a3;
	let t6;
	let t7;
	let li3;
	let a4;
	let t8;
	let t9;
	let a5;
	let t10;

	return {
		c() {
			nav = element("nav");
			a0 = element("a");
			img = element("img");
			t0 = space();
			button = element("button");
			i = element("i");
			t1 = space();
			div = element("div");
			ul = element("ul");
			li0 = element("li");
			a1 = element("a");
			t2 = text("Blog");
			t3 = space();
			li1 = element("li");
			a2 = element("a");
			t4 = text("Pricing");
			t5 = space();
			li2 = element("li");
			a3 = element("a");
			t6 = text("Contact");
			t7 = space();
			li3 = element("li");
			a4 = element("a");
			t8 = text("FAQ");
			t9 = space();
			a5 = element("a");
			t10 = text("Get Started");
			this.h();
		},
		l(nodes) {
			nav = claim_element(nodes, "NAV", { class: true });
			var nav_nodes = children(nav);
			a0 = claim_element(nav_nodes, "A", { class: true, href: true });
			var a0_nodes = children(a0);

			img = claim_element(a0_nodes, "IMG", {
				width: true,
				class: true,
				src: true,
				alt: true
			});

			a0_nodes.forEach(detach);
			t0 = claim_space(nav_nodes);

			button = claim_element(nav_nodes, "BUTTON", {
				class: true,
				type: true,
				"data-toggle": true,
				"data-target": true,
				"aria-expanded": true
			});

			var button_nodes = children(button);
			i = claim_element(button_nodes, "I", { class: true });
			children(i).forEach(detach);
			button_nodes.forEach(detach);
			t1 = claim_space(nav_nodes);
			div = claim_element(nav_nodes, "DIV", { class: true, id: true, style: true });
			var div_nodes = children(div);
			ul = claim_element(div_nodes, "UL", { class: true });
			var ul_nodes = children(ul);
			li0 = claim_element(ul_nodes, "LI", { class: true });
			var li0_nodes = children(li0);
			a1 = claim_element(li0_nodes, "A", { class: true, href: true });
			var a1_nodes = children(a1);
			t2 = claim_text(a1_nodes, "Blog");
			a1_nodes.forEach(detach);
			li0_nodes.forEach(detach);
			t3 = claim_space(ul_nodes);
			li1 = claim_element(ul_nodes, "LI", { class: true });
			var li1_nodes = children(li1);
			a2 = claim_element(li1_nodes, "A", { class: true, href: true });
			var a2_nodes = children(a2);
			t4 = claim_text(a2_nodes, "Pricing");
			a2_nodes.forEach(detach);
			li1_nodes.forEach(detach);
			t5 = claim_space(ul_nodes);
			li2 = claim_element(ul_nodes, "LI", { class: true });
			var li2_nodes = children(li2);
			a3 = claim_element(li2_nodes, "A", { class: true, href: true });
			var a3_nodes = children(a3);
			t6 = claim_text(a3_nodes, "Contact");
			a3_nodes.forEach(detach);
			li2_nodes.forEach(detach);
			t7 = claim_space(ul_nodes);
			li3 = claim_element(ul_nodes, "LI", { class: true });
			var li3_nodes = children(li3);
			a4 = claim_element(li3_nodes, "A", { class: true, href: true });
			var a4_nodes = children(a4);
			t8 = claim_text(a4_nodes, "FAQ");
			a4_nodes.forEach(detach);
			li3_nodes.forEach(detach);
			ul_nodes.forEach(detach);
			t9 = claim_space(div_nodes);
			a5 = claim_element(div_nodes, "A", { href: true, class: true });
			var a5_nodes = children(a5);
			t10 = claim_text(a5_nodes, "Get Started");
			a5_nodes.forEach(detach);
			div_nodes.forEach(detach);
			nav_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(img, "width", "200px");
			attr(img, "class", "img-fluid");
			if (img.src !== (img_src_value = "assets/logo.png")) attr(img, "src", img_src_value);
			attr(img, "alt", "Bigspring Hugo");
			attr(a0, "class", "navbar-brand");
			attr(a0, "href", ".");
			attr(i, "class", "ti-menu h3");
			attr(button, "class", "navbar-toggler border-0 collapsed");
			attr(button, "type", "button");
			attr(button, "data-toggle", "collapse");
			attr(button, "data-target", "#navigation");
			attr(button, "aria-expanded", "false");
			attr(a1, "class", "nav-link");
			attr(a1, "href", "blog");
			attr(li0, "class", "nav-item");
			attr(a2, "class", "nav-link");
			attr(a2, "href", "pricing");
			attr(li1, "class", "nav-item");
			attr(a3, "class", "nav-link");
			attr(a3, "href", "contact");
			attr(li2, "class", "nav-item");
			attr(a4, "class", "nav-link");
			attr(a4, "href", "faq");
			attr(li3, "class", "nav-item");
			attr(ul, "class", "navbar-nav mx-auto");
			attr(a5, "href", "contact");
			attr(a5, "class", "btn btn-sm btn-primary ml-3");
			attr(div, "class", "navbar-collapse text-center collapse");
			attr(div, "id", "navigation");
			attr(nav, "class", "navbar navbar-expand-lg navbar-light bg-transparent");
		},
		m(target, anchor) {
			insert(target, nav, anchor);
			append(nav, a0);
			append(a0, img);
			append(nav, t0);
			append(nav, button);
			append(button, i);
			append(nav, t1);
			append(nav, div);
			append(div, ul);
			append(ul, li0);
			append(li0, a1);
			append(a1, t2);
			append(ul, t3);
			append(ul, li1);
			append(li1, a2);
			append(a2, t4);
			append(ul, t5);
			append(ul, li2);
			append(li2, a3);
			append(a3, t6);
			append(ul, t7);
			append(ul, li3);
			append(li3, a4);
			append(a4, t8);
			append(div, t9);
			append(div, a5);
			append(a5, t10);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(nav);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;